Gaussian:
  sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre_0:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
  centre_1:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
  ell_comps_0:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: -1.0
      upper: 1.0
GaussianSph:
  sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre_0:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
  centre_1:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
