Moffat:
  alpha:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  beta:
    type: Uniform
    lower_limit: 1.0
    upper_limit: 5.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre_0:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
  centre_1:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
  ell_comps_0:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Uniform
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
MoffatSph:
  alpha:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  beta:
    type: Uniform
    lower_limit: 1.0
    upper_limit: 5.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre_0:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
  centre_1:
    type: Uniform
    lower_limit: -0.3
    upper_limit: 0.3
    width_modifier:
      type: Absolute
      value: 1.5
    gaussian_limits:
      lower: inf
      upper: -inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
